version: '3'
services:
  redis:
    hostname: redis
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    command: redis-server /etc/redis/redis.conf
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./data:/data/redis/data # redis.conf中的dir路径也需保持一致
      - ./conf:/etc/redis
      - ./logs:/data/redis/logs
    ports:
      - "8379:6379"
    networks:
      docker-network

networks:
  docker-network:
    name: docker-network # 网络名称
    driver: bridge
      