version: '3.7'
services:
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    hostname: php
    container_name: php
    restart: unless-stopped
    volumes:
      - ./html:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - docker-network     

networks:
  docker-network:
    name: docker-network # 网络名称
    driver: bridge