version: '3.7'
services:
  elasticsearch:
    hostname: elasticsearch
    container_name: elasticsearch
    image: elasticsearch:6.8.6
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/usr/share/elasticsearch/data     # 数据目录
      - ./conf:/usr/share/elasticsearch/config   # 配置目录
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - docker-network

networks:
  docker-network:
    name: docker-network
    driver: bridge

