version: '3.7'
services:
  mysql:
    hostname: mysql
    image: mysql:5.7.28
    container_name: mysql
    restart: unless-stopped
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #设置utf8字符集
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql/conf:/etc/mysql
    ports:
      - "8306:3306"
    networks:
      - docker-network

  redis:
    hostname: redis
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    command: redis-server /etc/redis/redis.conf
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./redis/data:/data/redis/data # redis.conf中的dir路径也需保持一致
      - ./redis/conf:/etc/redis
      - ./redis/logs:/data/redis/logs
    ports:
      - "8379:6379"
    networks:
      - docker-network

  nginx:
    hostname: nginx
    image: nginx:1.16.1
    container_name: nginx
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/logs:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - docker-network

  nps:
    hostname: nps
    image: fank243/nps:latest
    container_name: nps
    restart: unless-stopped
    volumes:
      - ./nps/conf:/nps/conf
    ports:
      - "8080:8080"
      - "8024:8024"
    networks:
      - docker-network

  yapi:
    hostname: yapi
    image: jayfong/yapi:latest
    container_name: yapi
    restart: unless-stopped
    volumes:
      - ./yapi/conf/config.json:/yapi/config.json
    ports:
      - "8300:3000"
    depends_on:
      - mongo
    networks:
      - docker-network

  mongo:
    hostname: mongo
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=yapi
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro
    ports:
      - "8270:27017"
    networks:
      - docker-network

networks:
  docker-network:
    name: docker-network