version: '3.7'
services:
  nginx:
    hostname: nginx
    image: nginx:1.16.1
    container_name: nginx
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html
      - ./logs:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      docker-network

networks:
  docker-network:
    name: docker-network
    driver: bridge
      
